services:
  frontend:
    build: ./FRONTEND
    container_name: vite_gourmand_front
    volumes:
      - ./FRONTEND:/usr/local/apache2/htdocs/

    ports:
      - "8080:80"

  api:
    build: ./BACKEND
    container_name: vite_gourmand_back
    ports:
      - "8000:80"
    volumes:
      - ./BACKEND:/var/www/html
      - symfony_var:/var/www/html/var   # ← ajout
      - symfony_vendor:/var/www/html/vendor   # ← ajout
    depends_on:
      - database
    environment:
      MAILER_DSN: "smtp://acf1e19e0218c6:b3254a640fa61a@sandbox.smtp.mailtrap.io:2525"

  # Ta base de données
  database:
    image: mysql:8
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viteEtGourmand_clean
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      
  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  symfony_var:
  symfony_vendor:
  db_data:
  mongo_data: