services:
  frontend:
    build: ./FRONTEND
    container_name: vite_gourmand_front
    volumes:
      - ./FRONTEND:/usr/share/nginx/html
    ports:
      - "8080:80"

    depends_on:
      - api  
  api:
    build: ./BACKEND
    container_name: vite_gourmand_back
    ports:
      - "8000:80"
    volumes:
      - ./BACKEND:/var/www/html
      
    depends_on:
      - database
    environment:
      APP_ENV: dev
      APP_DEBUG: 1 
      MAILER_DSN: "smtp://acf1e19e0218c6:b3254a640fa61a@sandbox.smtp.mailtrap.io:2525"
      DATABASE_URL: "postgresql://postgres:1234@database:5432/viteEtGourmand_clean?serverVersion=16&charset=utf8"

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: viteEtGourmand_clean
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  db_data:
  mongo_data: