<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260729134222 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(50) DEFAULT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contact_msg (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, message TEXT NOT NULL, email VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, traite BOOLEAN DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_95B03E97A76ED395 ON contact_msg (user_id)');
        $this->addSql('CREATE TABLE dish_allergen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dish_id INT DEFAULT NULL, allergen_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3C4389A5148EB0CB ON dish_allergen (dish_id)');
        $this->addSql('CREATE INDEX IDX_3C4389A56E775A4A ON dish_allergen (allergen_id)');
        $this->addSql('CREATE TABLE dishes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description TEXT NOT NULL, price NUMERIC(10, 2) NOT NULL, category VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menus (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description_menu TEXT NOT NULL, picture TEXT DEFAULT NULL, min_people INT NOT NULL, price NUMERIC(10, 2) NOT NULL, conditions TEXT DEFAULT NULL, stock INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, theme_menu VARCHAR(255) DEFAULT NULL, diet_menu VARCHAR(255) DEFAULT NULL, order_before INT NOT NULL, is_available BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menus_dishes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, display_order INT NOT NULL, menu_id INT DEFAULT NULL, dish_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_877C5E79CCD7E912 ON menus_dishes (menu_id)');
        $this->addSql('CREATE INDEX IDX_877C5E79148EB0CB ON menus_dishes (dish_id)');
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number_of_people INT NOT NULL, total_price DOUBLE PRECISION NOT NULL, delivery_cost DOUBLE PRECISION DEFAULT NULL, delivery_address VARCHAR(255) NOT NULL, delivery_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivery_time TIME(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, cancellation_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, delivery_city VARCHAR(50) NOT NULL, delivery_postal_code INT NOT NULL, concaled_by VARCHAR(100) DEFAULT NULL, user_id INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEEA76ED395 ON orders (user_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEECCD7E912 ON orders (menu_id)');
        $this->addSql('CREATE TABLE reviews (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, is_validated BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6970EB0F82EA2E54 ON reviews (commande_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, address TEXT DEFAULT NULL, phone INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, api_token VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE contact_msg ADD CONSTRAINT FK_95B03E97A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE dish_allergen ADD CONSTRAINT FK_3C4389A5148EB0CB FOREIGN KEY (dish_id) REFERENCES dishes (id)');
        $this->addSql('ALTER TABLE dish_allergen ADD CONSTRAINT FK_3C4389A56E775A4A FOREIGN KEY (allergen_id) REFERENCES allergens (id)');
        $this->addSql('ALTER TABLE menus_dishes ADD CONSTRAINT FK_877C5E79CCD7E912 FOREIGN KEY (menu_id) REFERENCES menus (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menus_dishes ADD CONSTRAINT FK_877C5E79148EB0CB FOREIGN KEY (dish_id) REFERENCES dishes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEECCD7E912 FOREIGN KEY (menu_id) REFERENCES menus (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reviews ADD CONSTRAINT FK_6970EB0F82EA2E54 FOREIGN KEY (commande_id) REFERENCES orders (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact_msg DROP CONSTRAINT FK_95B03E97A76ED395');
        $this->addSql('ALTER TABLE dish_allergen DROP CONSTRAINT FK_3C4389A5148EB0CB');
        $this->addSql('ALTER TABLE dish_allergen DROP CONSTRAINT FK_3C4389A56E775A4A');
        $this->addSql('ALTER TABLE menus_dishes DROP CONSTRAINT FK_877C5E79CCD7E912');
        $this->addSql('ALTER TABLE menus_dishes DROP CONSTRAINT FK_877C5E79148EB0CB');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEA76ED395');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEECCD7E912');
        $this->addSql('ALTER TABLE reviews DROP CONSTRAINT FK_6970EB0F82EA2E54');
        $this->addSql('DROP TABLE allergens');
        $this->addSql('DROP TABLE contact_msg');
        $this->addSql('DROP TABLE dish_allergen');
        $this->addSql('DROP TABLE dishes');
        $this->addSql('DROP TABLE menus');
        $this->addSql('DROP TABLE menus_dishes');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE reviews');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
